# Copyright (c) 2023, Bennett Samowich <bennett@foolean.org>
# All rights reserved
# SPDX short identifier: BSD-3-Clause
---

# We put the entire role in a block so we can create
# a role specific tag, which saves the caller from
# having to do so in their playbook.
- name: Role foolean/gnome
  block:

    - name: Set OS variables
      ansible.builtin.include_vars:
        file: "{{ item }}"
      with_first_found:
        - "{{ ansible_os_family|lower }}.yml"
        - "default.yml"

    - name: CIS | Ensure GNOME Display Manager is removed
      become: true
      ansible.builtin.package:
        name: "{{ gnome_packages }}"
        state: "{{ gnome_gdm_state }}"

    - name: CIS | Ensure GDM login banner is configured (part-1)
      become: true
      ansible.builtin.template:
        src: 'etc/dconf/profile/gdm.j2'
        dest: '/etc/dconf/profile/gdm'
        owner: 'root'
        group: 'root'
        mode: '0644'
      notify: Update dconf
      when:
        - gnome_gdm_state == 'present'

    - name: CIS | Ensure GDM login banner is configured (part-2)
      become: true
      ansible.builtin.template:
        src: 'etc/dconf/db/gdm.d/01-banner-message.j2'
        dest: '/etc/dconf/db/gdm.d/01-banner-message'
        owner: 'root'
        group: 'root'
        mode: '0644'
      notify: Update dconf
      when:
        - gnome_gdm_state == 'present'

    - name: CIS | Ensure last logged in user display is disabled
      become: true
      ansible.builtin.template:
        src: 'etc/dconf/db/gdm.d/00-login-screen.j2'
        dest: '/etc/dconf/db/gdm.d/00-login-screen'
        owner: 'root'
        group: 'root'
        mode: '0644'
      notify: Update dconf
      when:
        - gnome_gdm_state == 'present'

    - name: CIS | Ensure XDMCP is not enabled
      become: true
      community.general.ini_file:
        path: '/etc/gdm/custom.conf'
        section: 'xdmcp'
        option: 'Enable'
        state: absent
        owner: 'root'
        group: 'root'
        mode: '0644'
      notify: Update dconf
      when:
        - gnome_gdm_state == 'present'

    - name: CIS | Ensure automatic mounting of removable media is disabled (dir)
      become: true
      ansible.builtin.file:
        name: '/etc/dconf/db/local.d'
        state: directory
        owner: 'root'
        group: 'root'
        mode: '0755'

    - name: CIS | Ensure automatic mounting of removable media is disabled (config)
      become: true
      ansible.builtin.template:
        src: 'etc/dconf/db/local.d/00-media-automount.j2'
        dest: '/etc/dconf/db/local.d/00-media-automount'
        owner: 'root'
        group: 'root'
        mode: '0644'
      notify: Update dconf

  # Tags to be applied to this role (block)
  tags:
    - 'role_foolean_gnome'
